### ISSUE TITLE
Add PlaceholderAPI Support for BetterHud texts

### ISSUE THREAD

**Issue by Moki0** [toxicity188/BetterHud#102]
Hello,

I was wondering if it would be possible to add support for PlaceholderAPI variables, as this would provide greater customization and flexibility for the plugin. For example, being able to use a placeholder like %betterhud_text_default_23_Hello World% to retrieve the text with the default font, a y-axis value of 23, and the content "Hello World." This would be similar to writing the following in the layouts:

```
texts:
  1:
    name: default
    pattern: "Hello World" 
    align: right
    x: -2
    y: 23
    space: 0
    scale: 0.5
    color: "white"
```
This would allow dynamic retrieval of the corresponding text in other parts of the game, greatly enhancing the plugin's versatility and customization options.

Thank you!
