### ISSUE TITLE
Fancy heads are rendering a bit wrong

### ISSUE THREAD

**Issue by PSYCHEER** [toxicity188/BetterHud#113]
![Image](https://github.com/user-attachments/assets/8162b4d4-e2f6-41cd-8919-1845551d8796)

![Image](https://github.com/user-attachments/assets/f9747cd7-f7bf-4177-8623-544ac1278de4)

Paper 1.21.4

```yaml
player:
  heads:
    1:
      name: hud_head
      type: fancy
      x: 41
      y: 58
```

```yaml
hud_head:
  pixel: 4
```

It looks the head overlay (hair layer) is shifted a bit
