### ISSUE TITLE
mmocore cooldown skill problem

### ISSUE THREAD

**Issue by MINIMANGITGUB** [toxicity188/BetterHud#25]
the picture appears but does not change over time. If you use standard mmocore skills then everything works as it should
```
voin_i_i:
  type: single
  file: voin_i_i.png

voin_i_i_cooldown:
  type: listener
  file: skill_cooldown.png
  split-type: up
  setting:
    listener:
      class: mmocore_cooldown_skill
      skill: VOIN_I_I
```
