### ISSUE TITLE
Pointers things

### ISSUE THREAD

**Issue by PSYCHEER** [toxicity188/BetterHud#45]
BetterHUD pointers are not saved(using yml filesystem in database.yml) after restart of server.
They actually doesn't take <icon> fontimages defined in font.yml files, tried to set it into "chain" but still showing only the pointer triangle.

REQUESTS
Pointers save
Global pointers(will be add to every player, not only to one defined in command)
Pointer fallout - when you will be like 20 blocks away(will be configurable) pointer will be hidden, so it will not mess with others

**Comment by PSYCHEER** [comment]
```yml
  images:
    map:
      name: "new-hud/icons/map.png"
      x: -7
      y: 1
      scale: 1.1
    claim:
      name: "new-hud/icons/claim.png"
      x: -7
      y: 1
      scale: 1.1
    bp:
      name: "new-hud/icons/bp.png"
      x: 0
      y: -10
      scale: 3
    votekey:
      name: "new-hud/icons/votekey.png"
      x: -5
      y: -2
      scale: 2
      ```

![{DAAFEB09-D54F-43A6-9F8A-79DEC8383CD5}](https://github.com/user-attachments/assets/510ff918-0419-4067-92c8-83f71ceb5049)
![{5ECF06DF-22C3-4092-BBED-E51DFA9E7E3B}](https://github.com/user-attachments/assets/56b46232-b185-4845-b496-e06b73da3ee2)
