### ISSUE TITLE
Bossbar merge issue with others plugins

### ISSUE THREAD

**Issue by SuperMax8** [toxicity188/BetterHud#46]
Bossbar from other plugins shown directly at the player join shift the whole hud down

When it's shifted toggle the hud change nothing, but when I toggle the bossbar it comes back to normal with proper bossbar merge

- Server version -> 1.20.4
- Server platform -> purpur
- bhud version -> BetterHud-1.6.253.jar
![image](https://github.com/user-attachments/assets/c4151cbb-f35d-47cd-aea2-152ff726051e)
![image](https://github.com/user-attachments/assets/fc925663-3f02-4874-9d62-89a9a50444f2)

Bhud config
```yml
debug: false
metrics: true
version-check: true
number-format: '#,###.#'
tick-speed: 1
namespace: betterhud
default-font-name: font.ttf
bossbar-line: 1
merge-boss-bar: true
disable-to-bedrock-player: true
build-folder-location: BetterHud/build
pack-type: zip
enable-protection: false
enable-self-host: false
force-update: false
self-host-ip: '*'
self-host-port: 8163
merge-other-folders: []
loading-head: random
default-hud:
- mmo_hud
default-popup: []
default-compass: []
disable-link-plugin: []
load-minecraft-default-textures: false
included-minecraft-list:
- block
- item
resourcepack-obfuscation: false
clear-build-folder: true
legacy-serializer: ampersand
minecraft-jar-version: bukkit
use-legacy-format: true
```
