### ISSUE TITLE
“Feature Request: Support for PlaceholderAPI Variables in BetterHud Text”

### ISSUE THREAD

**Issue by Moki0** [toxicity188/BetterHud#51]
Dear BetterHud plugin author,

Your BetterHud plugin has been incredibly helpful for my creations. It would be even better if it could include the following feature. 

Feature suggestion: Please add support for PlaceholderAPI variables, such as `%betterhud_text_Hello!%`, which would result in the text "Hello." Since your plugin’s text feature is so powerful, I would love to be able to apply it in other areas as well.

Thank you for all the support your plugin has provided!

**Comment by kombykorm** [comment]
nice

**Comment by toxicity188** [comment]
Now you can test BH's placeholder by /hud parse [text]

**Comment by Moki0** [comment]
No, what I mean is that I want to call a string via PAPI, similar to how it is written in layouts:

```
texts:
  1:
    name: default
    pattern: "Hello World" 
    align: right
    x: -2
    y: 23
    space: 0
    scale: 0.5
    color: "white"
```
So, is it possible to use PAPI like %betterhud_text_default_23_Hello World% to retrieve the corresponding string and display it anywhere PAPI can be used, such as in InventoryView or ItemStack?
