### ISSUE TITLE
Optimizing the name Field: Enabling Placeholder Support for Greater Flexibility.

### ISSUE THREAD

**Issue by Moki0** [toxicity188/BetterHud#54]
Thank you for your outstanding work on this project; it has been a pleasure to use and contribute to it. I would like to propose a small enhancement to optimize the functionality of partner_state_head in the configuration.

Currently, the name field requires explicit values for each type, as shown below:

```
partner_state_head:
  images:
    1:
      name: ice_knight
      x: -17
      y: 19
      scale: 0.16
      conditions:
        1:
          first: "string:animalpartner_carry_0_type"
          second: "'ice_knight'"
          operation: '=='
    2:
      name: dark_imp
      x: -17
      y: 19
      scale: 0.16
      conditions:
        1:
          first: "string:animalpartner_carry_0_type"
          second: "'dark_imp'"
          operation: '==' 
```
To improve flexibility and reduce redundancy, I propose allowing the name field to support PlaceholderAPI (PAPI) strings. For example:

```
partner_state_head:
  images:
    1:
      name: [string:animalpartner_carry_0_type]
      x: -17
      y: 19
      scale: 0.16
      conditions:
        1:
          first: "string:animalpartner_carry_0_type"
          second: "'null'"
          operation: '!='
```
This change would enable dynamic value assignment based on the string:animalpartner_carry_0_type placeholder, streamlining configuration for users who handle multiple types.
