### ISSUE TITLE
Split-Type: Left With 0.5 Scale Not Working As Intended 

### ISSUE THREAD

**Issue by DrakerSAN** [toxicity188/BetterHud#61]
In the BetterHud plugin, when I go into the default-image.yml file and change a code line to split-type: right and also have a default-layout.yml code line to scale: 0.5, it will have the image move right to left as the bar decreases. (the air bar is the example)

https://github.com/user-attachments/assets/a26fa73f-aa66-416d-b601-684364333fc1

![Screenshot 2024-12-02 115249](https://github.com/user-attachments/assets/8fc7098a-b52d-4faa-9534-2fc9aae70a19)

```
air_bar:
  type: listener
  file: air_bar.png
  split: 25
  split-type: right
  setting:
    listener:
      class: air
```

![Screenshot 2024-12-02 115301](https://github.com/user-attachments/assets/85aeff6d-c8ee-44d1-8c57-463bbebe72d7)

```
air:
  images:       
    1:
      name: air_empty
      x: 49
      y: 16
      scale: 0.5       
    2:
      name: air_bar
      x: 49
      y: 16
      scale: 0.5   
```

OS: Windows 10 Pro (Virtual Machine Setup)
Server Version: 1.20.4 
Server Platform: Paper (paper-1.20.4-499)

Tested on a Vanilla Client*

**Comment by toxicity188** [comment]
https://github.com/toxicity188/BetterHud/wiki/images

**Comment by DrakerSAN** [comment]
I have looked at the wiki on images, but could not find a solution to my issue, I have changed it to scale: 1 and that seems to fix it, but I want to use scale: 0.5 but it still moves left to right multiple times no matter what I do to it. Only thing I can think of its a bug, unless I'm overlooking something simple.

**Comment by toxicity188** [comment]
I checked again and i found that this is happened even calculation is correct.

Maybe, for now, you have to use **render-scale** instead of scale

```yaml
# layout
render-scale:
  x: 0.5
  y: 0.5
```
