### ISSUE TITLE
Feature request for values less than 1 in "space" parameter for layouts

### ISSUE THREAD

**Issue by quillincn** [toxicity188/BetterHud#62]
The suggestion is to allow **"space: 1"** in layouts to work with values **less** than **1**. Currently, setting it to **0** or a **negative** value **(e.g., -1)** has no effect. This change would simplify certain tasks, such as working with bitmaps or similar cases where it is necessary to reduce the space between characters. Currently, you can only increase the spacing, not decrease it.

For example, in my case, I'm trying to fit several values into a **single row** as a **single layout** with its **own** background (otherwise I cannot split the background for a layout), to **avoid overlapping** if the 1st value became too wide and covered the 2nd. I decided to use a bitmap font texture with **background** in it to achieve this. If I split it into two layouts, the first **1st** would overlap the **2nd** one if it got too long.

<details>
<summary>Screenshots/bitmap/settings for explanation:</summary>

![1](https://github.com/user-attachments/assets/5876c14d-04c5-4462-8a94-0ac956af6efb)
![2](https://github.com/user-attachments/assets/63562e55-2190-4c39-9cf8-34ba83297480)
![3](https://github.com/user-attachments/assets/79c37ae7-9393-4e07-9d81-a2c7dbd97cb7)

Font config:
```yaml
stats_font:
  type: bitmap
  chars:
    1:
      file: "font/stats_font.png"
      codepoints:
       - "{0123456789BKM}" # Those "{}" will be used as the background sides.
```

Bitmap texture (with background and sides):
![stats_font](https://github.com/user-attachments/assets/eb91252a-f75a-4f1a-a6e7-a3701eec8752)

Layout config:
```yaml
stats:
  texts:
    1:
      name: stats_font
      space: 0
      align: left
      pattern: "{<space:-1>1234567<space:-1>}<space:4>{<space:-1>421<space:-1>}" # In this case, I tried to add the background inside the bitmap along with corners, placing both values in a single layout. This way, if the first value becomes wider, the second one will shift automatically.
      x: -89
      y: 22
```

</details>

**Comment by toxicity188** [comment]
Probably bug; now available in [Modrinth](https://modrinth.com/plugin/betterhud2/version/vCOd7PAs)

**Comment by quillincn** [comment]
> Probably bug; now available in [Modrinth](https://modrinth.com/plugin/betterhud2/version/vCOd7PAs)

Really appreciate the quick response and your work, thanks a lot! 🤝

Unfortunately, it's still not possible to make "space" inside the layout work with values below 1. Maybe I'm doing something wrong or maybe I explained the problem not really clear, if so, sorry, my bad. 

Just in case, I'm talking about parameters `space: value_below_1` [inside layout parameters block](https://github.com/toxicity188/BetterHud/wiki/layouts#space), not about `<space:some_value>` tag inside **pattern** line.



<details>
<summary>More details</summary>

---
I tested `BetterHud-1.9.2.DEV-316-bukkit.jar` and `BetterHud-1.9.2.DEV-317-bukkit.jar` builds on the `1.21.1-131-ver/1.21.1@84281ce` version of PaperMC. 

When setting `space: 1` to any value above `1`, the layout increases the space between characters. However, setting it to a value below `1` (`space: -5` for example) resets it to the default spacing (equal to 1). Updating the resource pack and reloading it sadly doesn’t affect it.

---

Test configs:

`BetterHud\layouts\stats-layout.yml` with bitmap font (stats_font)
```
stats:
  texts:
    1:
      name: stats_font
      space: -5 # just in case I am talking about this parameter
      align: left
      pattern: "{123456}"
      x: -89
      y: 12
```
![изображение](https://github.com/user-attachments/assets/9f27e5e7-9b43-40fa-ba12-2a65f3535a49)

---

`BetterHud\layouts\stats-layout.yml` with default font (default_font)

```
stats:
  texts:
    1:
      name: default_font # default font
      space: -5 
      align: left
      pattern: "{123456}"
      x: -89
      y: 12
```

![изображение](https://github.com/user-attachments/assets/973d842b-a680-4c46-b136-8be1412ba225)

</details>
