### ISSUE TITLE
Health listener format issue

### ISSUE THREAD

**Issue by LuluxClient** [toxicity188/BetterHud#65]
**Required**  
When using the health listener like this:
```YAML
health_bar:
  type: listener
  file: health_bar.png
  split: 25
  split-type: left
  setting:
    listener:
      class: health
```
it won't output the health value normaly with but with 34123 decimals. If possible to remove them and not have decimal numbers for the health value. 

1. Tell me the detail about your problem.

2. Upload some screenshot or text log related your issue. such as:
```YAML
health_bar:
  type: listener
  file: health_bar.png
  split: 25
  split-type: left
  setting:
    listener:
      class: health
```
![image](https://github.com/user-attachments/assets/272e9557-9f70-4f59-bc22-d0d90ac81141)

3. Remember to notice your environment
- OS windows
- Server version: 1.21.3
- Server platform paper

**Disclaimer**  
I do NOT provide any solution about that.

- Using informal launcher such as Feather client
- Closed-source plugin/mod such as Optifine and ItemsAdder
- Usage in hybrid bukkit such as ArcLight
