### ISSUE TITLE
Fabric Placeholder Conditions buggy, and request pattern for correct usage of Has_Permission arg

### ISSUE THREAD

**Issue by SimonMage** [toxicity188/BetterHud#68]
Please could you tell me the placeholder condition pattern for fabric?
Placeholders in fabric are like modId:placeholder and I guess this doesn't work correctly with papi args of better hud.

I need also the pattern for has_permission because I can't find it working in my tests

I'm searching from days but I can't find them working, please I really need the correct pattern usage for fabric.
In the wiki is only written "has_permission:arg" and "papi_parse_for:arg" that doesn't help me

I guess this is an issue of the mod for fabric:

[17:00:29] [Thread-50/WARN]: Unable to load this condition: main
[17:00:29] [Thread-50/WARN]: Reason: this placeholder not found: [placeholder_api_parse

in layout:
```
conditions:
    main:
      first: "[placeholder_api_parse:instancemod:name]"
      second: "'Volo'"
      operation: "!="
```

what am I doing wrong?

in layout withaout brackets I have no errors but the placeholder doesn't work in conditions:
```
conditions:
    main:
      first: "placeholder_api_parse:instancemod:name"
      second: "'Volo'"
      operation: "!="

```
The placeholder used in text works with no issues, only conditions have this problem in fabric
