### ISSUE TITLE
Any feature

### ISSUE THREAD

**Issue by Thebestharrison1221** [toxicity188/BetterHud#70]
**Required**  
a way to change the player head

i would like a way to be able to do like /sethead (playername) with skript or something and it will change the texture of the head on screen idk if its possible to change it manually beacause its not in wiki if it is or fi it is i cant find it but that would be great

**Comment by toxicity188** [comment]
Already exists.
```yaml
some_head_layout:
  name: some_head
  follow: "some_player_name_placeholder"
```
