### ISSUE TITLE
Placeholder to check if the player is under water

### ISSUE THREAD

**Issue by Ranksu10** [toxicity188/BetterHud#77]
It could be a good idea to implement a placeholder that recognizes if the player in under water (or has the bubbles hud triggered)
![image](https://github.com/user-attachments/assets/d528223c-c659-4822-8e53-3f874926befa)

This is specially to avoid this kind of situations (image above).

Currently, there is no placeholder that recognizes that.

%player_remaining_air% works but not when the player has water breathing effect.
Adding another condition like %player_has_potioneffect_water_breathing% will just make both conditions enter in conflict and will not properly work.

**Comment by toxicity188** [comment]
Currently, you can use 'air'
```yaml
layout_bubble:
  images:
    bubble:
      name: image_bubble
      stack: "air@t/32-1/10"
      layer: 1
      space: 2
      x: 22
      y: 2
      conditions:
        1:
          first: air
          second: 300
          operation: "<"
        2:
          first: air
          second: 32
          operation: ">"
```
