### ISSUE TITLE
Head with type fancy is rendering incorrectly

### ISSUE THREAD

**Issue by Chronoken** [toxicity188/BetterHud#78]
**Issue:** Whenever you set the head type to `fancy`, it renders the outer head layer completely wrong, in different places (above/below or left/right to the first head layer)

**Screenshots:** How it looks like with the head type set to `fancy`:
![image](https://github.com/user-attachments/assets/09ac8b36-bd8a-456c-85d4-eeb5cf7e8a14)

**Configuration:**
How the head is defined in the `heads` folder:
```yaml
player_head:
    pixel: 2
```

How the head is defined in the `layouts` folder:
```yaml
head_layout:
    heads:
        0:
            name: player_head
            x: 11
            y: 65
            type: fancy
```

**Versions**:
- OS (Windows 11)
- PaperMC 1.21.3 (latest build 82)
- BetterHud 1.11.3
- BetterHealthBar 3.8.1 (it might be related to the issue but i tried removing BetterHealthBar, regenerating the resourcepack and the head layer position was still glitched)

**Comment by toxicity188** [comment]
Not happened in same setting.
![2025-01-11_21 11 57](https://github.com/user-attachments/assets/2c9ee7e3-a4d1-4906-9b3d-8c681103b47a)

**Comment by PSYCHEER** [comment]
![Image](https://github.com/user-attachments/assets/8162b4d4-e2f6-41cd-8919-1845551d8796)

![Image](https://github.com/user-attachments/assets/f9747cd7-f7bf-4177-8623-544ac1278de4)

```yaml
player:
  heads:
    1:
      name: hud_head
      type: fancy
      x: 41
      y: 58
```

```yaml
hud_head:
  pixel: 4
```

It looks the head overlay (hair layer) is shifted a bit
