### ISSUE TITLE
Head with follow placeholder and a condition stops rendering

### ISSUE THREAD

**Issue by Chronoken** [toxicity188/BetterHud#81]
**Issue:** Whenever you set the head with follow placeholder to track other players, it renders their head properly, but if you define any conditions under the head in the layout, or for the whole layout, the player head will never appear.

**Screenshots:** 
* How it looks like without any conditions for the head or the entire layout:
  ![Image](https://github.com/user-attachments/assets/9d923bff-eafe-4a9b-a6bb-e01bfd928118)

* How it looks if you define any condition for the head in the layout, or for the whole layout:
  ![Image](https://github.com/user-attachments/assets/0ddef520-08eb-4dc7-865a-5f366e6ed46f)

**Configuration:**
How the head is defined in the layouts folder:
```yaml
party_member_layout_1:
    heads:
        1:
            name: party_member_head
            x: 16
            y: 92
            follow: "papi:na_partymembers_ALLIANCETARGET_0"
    images:
        1:
            name: party_member_health_background
            scale: 0.95
            x: 14
            y: 90
        2:
            name: party_member_health_empty
            scale: 0.35
            x: 14
            y: 104
        3:
            name: party_member_health_red_1
            scale: 0.35
            x: 14
            y: 104
```
And this works completely fine, the head is always rendered.

How the head is defined with a condition for the whole layout:
```yaml
party_member_layout_1:
    heads:
        1:
            name: party_member_head
            x: 16
            y: 92
            follow: "papi:na_partymembers_ALLIANCETARGET_0"
    images:
        1:
            name: party_member_health_background
            scale: 0.95
            x: 14
            y: 90
        2:
            name: party_member_health_empty
            scale: 0.35
            x: 14
            y: 104
        3:
            name: party_member_health_red_1
            scale: 0.35
            x: 14
            y: 104
    conditions: 
        1:
            first: "papi:na_haspartymember_ALLIANCETARGET_0"
            second: "'true'"
            operation: '=='
```

How the head is defined with a condition for the head only:
```yaml
party_member_layout_1:
    heads:
        1:
            name: party_member_head
            x: 16
            y: 92
            follow: "papi:na_partymembers_ALLIANCETARGET_0"
            conditions: 
                1:
                    first: "papi:na_haspartymember_ALLIANCETARGET_0"
                    second: "'true'"
                    operation: '=='
    images:
        1:
            name: party_member_health_background
            scale: 0.95
            x: 14
            y: 90
        2:
            name: party_member_health_empty
            scale: 0.35
            x: 14
            y: 104
        3:
            name: party_member_health_red_1
            scale: 0.35
            x: 14
            y: 104
```

Both of those layouts where conditions are present, the head will disappear and never render again.
Also FYI, i tested the placeholders, i tried the built in placeholders from the wiki too, so its definitely an issue with the head rendering with the `follow` option

**Versions:**

    OS (Windows 11)
    PaperMC 1.21.4 (latest build 121)
    BetterHud 1.11.4
    BetterHealthBar 3.8.1
