### ISSUE TITLE
image papi error

### ISSUE THREAD

**Issue by dafsdfasde** [toxicity188/BetterHud#88]
Windows
1.20.1
paper

```
exp_bar:
  type: listener
  file: "exp_bar.png"
  split: 30
  split-type: left
  setting:
    listener:
      class: placeholder
      value: "(number)papi:level_exp"
      max: "(number)papi:level_require_exp"
```

It seems that the image does not display correctly when the PAPI values set in `value` and `max` exceed 1000.

The experience I am using is not vanilla experience, but a PAPI created by a level plugin.
