### ISSUE TITLE
Insufficient PAPI parsing of layout pattern

### ISSUE THREAD

**Issue by kyojioonaon** [toxicity188/BetterHud#93]
## Problem
I found a issue where notations that contain 'cient-side parsing' using PAPI could not be used in the layout pattern.

## Current situation

The contents of the placeholder are as follows
```
x1 Firebrand (string)
x2 <lang:item.minecraft.enchanted_golden_apple> (string)
```
![check](https://imgur.com/a3PpmyB.png)

`/hud parse` command had no problems at all.
However, when this is applied, only the lang tag section is not displayed correctly.

<img width="250" src="https://imgur.com/fygjXFh.png">

## Code
- popup layout
```
pickup_row_1:
  texts:
    seconds:
      name: tutorial_font
      pattern: "[papi:restsrv_pickup-row-1]"
      align: right
      x: 14
      y: 76
      space: 0
      scale: 0.5
      color: "white"
      outline: false
```

## Environment
- Server platform: Paper 1.21.4-147
- Pluign version: 1.11.4

Thanks
