### ISSUE TITLE
<none>'s head error

### ISSUE THREAD

**Issue by dafsdfasde** [toxicity188/BetterHud#94]
Windows
1.20.1
paper

betterhud 1.11.4

An error is displayed in the console when connecting to the server.

## console error logs
```
[06:03:16 WARN]: [BetterHud] Unable to get <none>'s head.
[06:03:16 WARN]: [BetterHud] Reason: Not a JSON Object: null
```

## BetterHud/layouts
```
party_head:
  heads:
    1:
      name: party_head
      x: 5
      y: 120
      follow: mmocore_party_member_exclude_mine:0
      conditions:
        1:
          first: gamemode
          second: "'SPECTATOR'"
          operation: "!="
```
